const state = { user:null, bootstrap:null, connected:false, page:'home', selectedSubmission:null };
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));

const ROLE_LABELS = {
  NC:'Nutrition Consultant', DATA_ENTRY:'Data Entry / Admin', DATA_ANALYST:'Data Analyst', PROJECT_MANAGER:'Project Manager'
};
const PAGE_META = {
  home:['TODAY','Dashboard'], visits:['FIELD PLAN','Today Visits'], tasks:['EXECUTION','Task List'], stock:['FIELD INPUT','Stock Taking'],
  offtake:['FIELD INPUT','Offtake'], sync:['OFFLINE FIRST','Sync Center'], history:['TRACEABILITY','Activity History'], profile:['ACCOUNT','My Profile'],
  queue:['DATA QUALITY','Data Control Center'], analytics:['PERFORMANCE','Program Dashboard'], performance:['PERFORMANCE','KPI Performance'],
  quality:['DATA QUALITY','Data Quality'], ncTracker:['FIELD FORCE','NC Tracker'], gwp:['GWP','GWP Monitoring'], consumer:['CONSUMER','Consumer Funnel'],
  competitor:['MARKET INTELLIGENCE','Competitor'], system:['SYSTEM','System Check']
};
const SIDE_NAV = {
  NC:[['home','⌂','Home'],['visits','⌖','Today Visits'],['tasks','☑','Task List'],['history','◷','History'],['sync','☁','Sync Center'],['profile','○','Profile'],['system','⚙','System Check']],
  DATA_ENTRY:[['queue','☑','Data Control Center'],['quality','◇','Data Quality'],['analytics','▦','Overview'],['system','⚙','System Check']],
  DATA_ANALYST:[['analytics','▦','Overview'],['performance','↗','KPI Performance'],['ncTracker','◎','NC Tracker'],['consumer','◇','Consumer'],['gwp','□','GWP'],['competitor','◈','Competitor'],['quality','☑','Data Quality'],['system','⚙','System Check']],
  PROJECT_MANAGER:[['analytics','▦','Executive Summary'],['performance','↗','Performance'],['ncTracker','◎','NC Tracker'],['consumer','◇','Consumer'],['gwp','□','GWP'],['competitor','◈','Competitor'],['quality','☑','Data Quality'],['system','⚙','System Check']]
};
const DESKTOP_TABS = [
  ['analytics','SUMMARY'],['performance','PERFORMANCE'],['gwp','GWP'],['consumer','CONSUMER'],['competitor','COMPETITOR'],['quality','DATA QUALITY'],['ncTracker','NC TRACKER']
];
const MOBILE_BOTTOM = [['home','⌂','Home'],['visits','⌖','Visit'],['tasks','☑','Task'],['history','◷','History'],['profile','○','Profile']];

window.addEventListener('DOMContentLoaded', init);
window.addEventListener('online',()=>{setConnection(true,'Internet online');flushOfflineQueue();});
window.addEventListener('offline',()=>setConnection(false,'Offline mode'));

async function init(){
  bindGlobal();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
  const saved=safeJson(localStorage.getItem('nc2027_user'));
  if(saved&&saved.userId){state.user=saved;showApp();await loadBootstrap();}
  updateOfflineBadge();
}
function bindGlobal(){
  $('#loginForm').addEventListener('submit',handleLogin);
  $$('.demo-account').forEach(b=>b.addEventListener('click',()=>{ $('#employeeCode').value=b.dataset.code; $('#pin').value='1234'; $('#loginForm').requestSubmit(); }));
  $('#togglePin').addEventListener('click',()=>{const p=$('#pin');p.type=p.type==='password'?'text':'password';});
  $('#logoutBtn').addEventListener('click',logout);
  $('#mobileMenuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
}
async function handleLogin(e){
  e.preventDefault(); const code=$('#employeeCode').value.trim().toUpperCase(), pin=$('#pin').value.trim(); setLoginBusy(true);
  try{const data=await api('login',{employeeCode:code,pin}); state.user=data.user; state.connected=true; persistUser(); showApp(); await loadBootstrap(); toast(`Selamat datang, ${state.user.fullName}`);}
  catch(err){const fallback=localLogin(code,pin); if(!fallback){toast(err.message||'Login gagal','error');}
    else{state.user=fallback;state.connected=false;persistUser();showApp();state.bootstrap=fallbackBootstrap(fallback);render();setConnection(false,'Offline demo fallback');toast('Backend belum terhubung. Demo tetap berjalan dengan fallback lokal.','warn');}}
  finally{setLoginBusy(false);}
}
function persistUser(){ if($('#rememberMe')?.checked!==false) localStorage.setItem('nc2027_user',JSON.stringify(state.user)); }
function setLoginBusy(b){const btn=$('#loginForm button[type="submit"]');btn.disabled=b;btn.textContent=b?'Menghubungkan…':'Login';}
function showApp(){
  $('#loginScreen').classList.add('hidden'); $('#appShell').classList.remove('hidden'); document.body.dataset.role=state.user.role;
  $('#userName').textContent=state.user.fullName; $('#userRole').textContent=ROLE_LABELS[state.user.role]||state.user.role; $('#userAvatar').textContent=initials(state.user.fullName);
  state.page=state.user.role==='NC'?'home':state.user.role==='DATA_ENTRY'?'queue':'analytics'; buildNavigation();
}
function buildNavigation(){
  const items=SIDE_NAV[state.user.role]||SIDE_NAV.NC;
  $('#navMenu').innerHTML=items.map(([k,i,l])=>`<button class="nav-item ${state.page===k?'active':''}" data-page="${k}"><span class="nav-ico">${i}</span>${escapeHtml(l)}</button>`).join('');
  $$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
  const tabs=$('#desktopTabs');
  if(state.user.role!=='NC'&&state.user.role!=='DATA_ENTRY'){tabs.classList.remove('hidden');tabs.innerHTML=DESKTOP_TABS.map(([k,l])=>`<button class="desktop-tab ${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));}
  else tabs.classList.add('hidden');
  const bottom=$('#mobileBottomNav');
  if(state.user.role==='NC'){bottom.classList.remove('hidden');bottom.innerHTML=MOBILE_BOTTOM.map(([k,i,l])=>`<button class="bottom-item ${state.page===k?'active':''}" data-page="${k}"><span class="bi">${i}</span><span>${l}</span></button>`).join('');bottom.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));}
  else bottom.classList.add('hidden');
}
async function loadBootstrap(){
  try{state.bootstrap=await api('bootstrap',{userId:state.user.userId});state.connected=true;setConnection(true,'GAS connected');}
  catch(_){state.bootstrap=fallbackBootstrap(state.user);state.connected=false;setConnection(false,'Offline demo fallback');}
  render(); if(navigator.onLine) flushOfflineQueue();
}
function go(page){state.page=page;$('#sidebar').classList.remove('open');buildNavigation();render();window.scrollTo({top:0,behavior:'smooth'});} window.go=go;
function render(){
  if(!state.user||!state.bootstrap)return; const [e,t]=PAGE_META[state.page]||['NC 2027','Dashboard']; $('#pageEyebrow').textContent=e; $('#pageTitle').textContent=t;
  const fn={home:renderHome,visits:renderVisits,tasks:renderTasks,stock:renderStock,offtake:renderOfftake,sync:renderSync,history:renderHistory,profile:renderProfile,queue:renderQueue,analytics:renderAnalytics,performance:renderPerformance,quality:renderQuality,ncTracker:renderNCTracker,gwp:renderGWP,consumer:renderConsumer,competitor:renderCompetitor,system:renderSystem}[state.page]||renderHome;
  $('#pageContent').innerHTML=fn(); bindPageEvents();
}
function bindPageEvents(){
  $('#stockForm')?.addEventListener('submit',submitStock); $('#offtakeForm')?.addEventListener('submit',submitOfftake);
  $('#systemStock')?.addEventListener('input',updateStockDiff); $('#physicalStock')?.addEventListener('input',updateStockDiff); updateStockDiff();
  $('#evidenceInput')?.addEventListener('change',previewEvidence);
  $$('.validate-btn').forEach(b=>b.addEventListener('click',()=>validationDecision(b.dataset.id,'VALIDATE')));
  $$('.correct-btn').forEach(b=>b.addEventListener('click',()=>openCorrectionModal(b.dataset.id)));
  $$('.submission-row').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('button'))return;openSubmissionModal(r.dataset.id);}));
  $('#refreshBtn')?.addEventListener('click',loadBootstrap); $('#healthBtn')?.addEventListener('click',checkHealth); $('#syncNowBtn')?.addEventListener('click',flushOfflineQueue);
  $('#applyFilter')?.addEventListener('click',()=>toast('Filter diterapkan untuk demo dashboard.')); $('#resetFilter')?.addEventListener('click',()=>{document.querySelectorAll('.filter-rail select').forEach(s=>s.selectedIndex=0);toast('Filter di-reset.');});
}

/* ---------- NC MOBILE ---------- */
function renderHome(){
  const b=state.bootstrap, tasks=(b.tasks&&b.tasks.length?b.tasks:mockTasks()), next=tasks.find(x=>x.status!=='COMPLETED')||tasks[0];
  return `<div class="mobile-only-content">
    <section class="mobile-hero"><small>Welcome to NC 2027</small><h3>Halo, ${escapeHtml(firstName(state.user.fullName))} 👋</h3><p>${formatLongDate(new Date())}</p></section>
    <div class="mobile-kpis">
      ${mobileStat(tasks.length,'Planned Visits')}${mobileStat(tasks.filter(x=>x.status==='COMPLETED').length||2,'Completed Visits')}${mobileStat((b.stats.taskCompletion||91)+'%','Task Completion')}${mobileStat('08:15','First Check-in')}
    </div>
    <div class="next-visit"><div class="next-visit-header"><b style="font-size:10px;color:#123C73">TODAY'S NEXT VISIT</b>${badge(next.status||'PLANNED')}</div><div class="next-visit-body"><h4>${escapeHtml(next.storeName)}</h4><p>Jl. Kemang Raya · Jakarta Selatan</p><div class="visit-meta"><span>◷ ${escapeHtml(next.plannedStart)}–${escapeHtml(next.plannedEnd)}</span><span>⌖ 1.2 km</span><span>8 tasks</span></div><button class="btn btn-primary btn-sm" onclick="go('visits')">View Visit</button></div></div>
    <div class="quick-title">QUICK ACCESS</div><div class="quick-grid">
      ${quick('⌖','PJP','visits')}${quick('☑','Task','tasks')}${quick('▣','Stock','stock')}${quick('↗','Offtake','offtake')}${quick('👥','Consumer','tasks')}${quick('☁','Sync','sync')}
    </div>
    <div class="section-title"><div><h3>Today Activity</h3><p>Progress store dari PJP hari ini.</p></div><span class="badge badge-blue">Live</span></div>
    <div class="visit-list">${tasks.slice(0,3).map((x,i)=>visitCard(x,i)).join('')}</div>
  </div>`;
}
function renderVisits(){const tasks=state.bootstrap.tasks?.length?state.bootstrap.tasks:mockTasks();return `<div class="info-strip">PJP menentukan store yang harus dikunjungi. GPS, waktu, dan user tercatat otomatis pada production flow.</div><div class="section-title"><div><h3>Today Visits</h3><p>${tasks.length} store dalam PJP hari ini.</p></div><span class="badge badge-blue">${formatShortDate(new Date())}</span></div><div class="visit-list">${tasks.map((x,i)=>visitCard(x,i,true)).join('')}</div>`;}
function renderTasks(){return `<div class="info-strip">NC cukup memilih task. Metadata seperti NC, region, area, tanggal, waktu dan store berasal dari sistem.</div>${taskSection('SALES & STOCK',[
  ['▣','Stock Taking','Daily','stock','active'],['▤','Share of Shelf','Bi-Weekly','tasks',''],['↗','Offtake','Daily','offtake','active'],['🎁','NTG & GWP','Daily','tasks','']])}${taskSection('STORE EXECUTION',[
  ['▧','Paid Visibility','Guideline','tasks',''],['₿','Price Monitoring','Bi-Weekly','tasks','warning']])}${taskSection('CONSUMER',[
  ['👤','Consumer Acquisition','Daily','tasks',''],['☷','Survey','Guideline','tasks','done']])}`;}
function taskSection(title,items){return `<div class="task-section-title">${title}</div><div class="task-grid">${items.map(([i,n,f,p,c])=>`<button class="task-tile ${c}" onclick="go('${p}')"><span class="task-icon">${i}</span><b>${n}</b><small>${f} · ${c==='done'?'Completed':c==='warning'?'Warning':'Pending'}</small></button>`).join('')}</div>`;}
function renderStock(){return `<form id="stockForm" class="form-card"><div class="form-title"><div><span class="overline">DAILY TASK</span><h3>Stock Taking</h3></div><span class="badge badge-blue">Guardian Kemang</span></div><div class="form-grid">
  ${storeSelect()}${productSelect()}<div class="field"><label>System Stock</label><input id="systemStock" name="systemStock" type="number" min="0" value="40" required></div><div class="field"><label>Physical Stock</label><input id="physicalStock" name="physicalStock" type="number" min="0" value="38" required></div>
  <div class="field span-2"><label>Difference · automatic</label><div class="stock-diff"><span>Physical − System</span><b id="stockDiff">-2</b></div></div>
  <div class="field span-2"><label>Photo Evidence</label><div class="evidence-box"><label for="evidenceInput">📷<b id="evidenceLabel">Take / Choose Photo</b><small>Demo preview only; backend schema tetap tidak diubah.</small></label><input id="evidenceInput" type="file" accept="image/*" capture="environment"></div></div>
  <div class="field span-2"><label>Remark</label><textarea name="remark" placeholder="Catatan bila diperlukan"></textarea></div></div>
  <div class="info-strip" style="margin-top:12px">Demo pitching: ubah <b>Physical Stock = 5</b>. Gap besar akan otomatis menjadi <b>WARNING</b> dan masuk Data Entry Queue.</div><div class="form-actions"><button class="btn btn-primary" type="submit">Submit Stock</button><button class="btn btn-ghost" type="button" onclick="go('tasks')">Cancel</button></div></form>`;}
function renderOfftake(){return `<form id="offtakeForm" class="form-card"><div class="form-title"><div><span class="overline">DAILY TASK</span><h3>Offtake</h3></div><span class="badge badge-blue">Structured Input</span></div><div class="form-grid">${storeSelect()}${productSelect()}<div class="field"><label>Quantity</label><input name="quantity" type="number" min="0" value="18" required></div><div class="field"><label>Value (optional)</label><input name="value" type="number" min="0" value="0"></div><div class="field span-2"><label>Source</label><select name="source"><option value="NC_INPUT">NC Input</option><option value="STORE_DATA">Store Data</option></select></div></div><div class="info-strip" style="margin-top:12px">Demo warning: quantity di atas <b>60</b> akan masuk exception queue.</div><div class="form-actions"><button class="btn btn-primary" type="submit">Submit Offtake</button><button class="btn btn-ghost" type="button" onclick="go('tasks')">Cancel</button></div></form>`;}
function renderSync(){const q=offlineQueue();return `${!navigator.onLine?`<div class="offline-callout"><b>⚠ You are offline</b><span>Don't worry. Your data is safely stored on this device.</span></div>`:''}<div class="sync-summary">${syncBox('✓',state.bootstrap.recentSubmissions?.length||24,'Synced')}${syncBox('⏳',q.length,'Waiting Sync')}${syncBox('!','0','Failed')}</div><div class="panel panel-pad" style="margin-top:12px"><div class="panel-head" style="padding:0 0 12px;border:0"><h3>Sync Status</h3><span class="badge ${state.connected?'badge-ok':'badge-warn'}">${state.connected?'Connected':'Fallback'}</span></div><p class="muted" style="font-size:11px;line-height:1.6">Last sync: ${new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}. Saat koneksi kembali, queue dikirim memakai idempotency key agar retry tidak membuat duplikat.</p><button id="syncNowBtn" class="btn btn-primary" style="width:100%;margin-top:8px">Sync Now</button></div>`;}
function renderHistory(){const rows=state.bootstrap.recentSubmissions||[];return `<div class="section-title"><div><h3>My Activity</h3><p>Submission dapat ditelusuri dari ID dan status validation.</p></div><button id="refreshBtn" class="btn btn-secondary btn-sm">Refresh</button></div>${rows.length?rows.map(r=>`<div class="history-card"><div class="history-top"><div><h4>${escapeHtml(r.store)}</h4><p>${escapeHtml(r.task)} · ${shortTime(r.time)}</p></div>${badge(r.status)}</div><p>Submission ${escapeHtml(shortId(r.submissionId))}</p></div>`).join(''):`<div class="panel panel-pad empty">Belum ada submission.</div>`}`;}
function renderProfile(){return `<div class="profile-card"><div class="profile-avatar">${initials(state.user.fullName)}</div><h3>${escapeHtml(state.user.fullName)}</h3><p>${escapeHtml(state.user.employeeCode||'NC001')} · ${escapeHtml(ROLE_LABELS[state.user.role])}</p><div class="grid-3" style="margin-top:18px">${miniProfile('Region','Jakarta')}${miniProfile('Area','South Jakarta')}${miniProfile('TL','Andi Setiawan')}</div><button class="btn btn-ghost" style="width:100%;margin-top:18px" onclick="logout()">Logout</button></div>`;}

/* ---------- DESKTOP / ANALYTICS ---------- */
function renderAnalytics(){const s=state.bootstrap.stats;return desktopWorkspace(`
  <div class="kpi-grid">${dashKpi('Active NC',s.activeNC,'+3 vs last month','up')}${dashKpi('Active Store',s.activeStores,'93% coverage','up')}${dashKpi('Achievement',(s.offtake||92)+'%','Target vs actual',s.offtake>=100?'up':'down')}${dashKpi('Task Completion',(s.taskCompletion||91)+'%','Field execution','up')}${dashKpi('Data Quality',(s.dataAccuracy||96.7)+'%','Validated data','up')}</div>
  <div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>Acquisition Performance</h3><p>Actual vs target · 7 day trend</p></div><span class="badge badge-blue">Live demo</span></div>${lineChart(state.bootstrap.trend||[])}</div><div class="panel"><div class="panel-head"><div><h3>Regional Performance</h3><p>Achievement by region</p></div><span class="badge badge-ok">92.4% avg</span></div>${regionBars(state.bootstrap.regionPerformance||[])}</div></div>
  <div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>Data Quality</h3><p>Operational confidence</p></div></div><div class="panel-pad" style="display:flex;gap:24px;align-items:center;justify-content:center"><div class="quality-donut" style="--p:${Number(s.dataAccuracy||96.7)}"><div><b>${s.dataAccuracy||96.7}%</b><span>PASS RATE</span></div></div><div style="min-width:190px">${metric('Completeness',98.6)}${metric('Timeliness',97.8)}${metric('Duplicate Rate',0.4,true)}${metric('Correction Rate',1.3,true)}</div></div></div><div class="panel"><div class="panel-head"><div><h3>Performance Insight</h3><p>Evidence-led interpretation</p></div></div><div class="panel-pad">${insightCard()}</div></div></div>
  <div class="section-title"><div><h3>Regional KPI Detail</h3><p>National → Region → Area → TL → NC → Store → Submission</p></div></div>${regionTable(state.bootstrap.regionPerformance||[])}
`);}
function renderPerformance(){const s=state.bootstrap.stats;return desktopWorkspace(`<div class="kpi-grid">${dashKpi('Acquisition',s.acquisition,'Monthly actual','up')}${dashKpi('Conversion',s.conversion,'Consumer conversion','up')}${dashKpi('Offtake',(s.offtake||92)+'%','Achievement','down')}${dashKpi('Coverage',(s.storeCoverage||93)+'%','Store coverage','up')}${dashKpi('GWP Absorption',(s.gwpAbsorption||87)+'%','Allocation used','up')}</div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>KPI Trend</h3><p>Target and actual</p></div></div>${lineChart(state.bootstrap.trend||[])}</div><div class="panel"><div class="panel-head"><div><h3>KPI Health</h3><p>Current month snapshot</p></div></div><div class="panel-pad">${metric('Acquisition',94)}${metric('Conversion',89)}${metric('Offtake',92)}${metric('Task Completion',s.taskCompletion||91)}${metric('Store Coverage',s.storeCoverage||93)}</div></div></div><div class="section-title"><div><h3>Target vs Actual</h3><p>Example KPI calculation layer.</p></div></div>${regionTable(state.bootstrap.regionPerformance||[])}`);}
function renderQueue(){const rows=state.bootstrap.queue||[],s=state.bootstrap.stats;return `<div class="kpi-grid">${dashKpi('Today Submissions',s.totalSubmissions||12542,'Raw + validated','up')}${dashKpi('Auto Pass',Math.max(0,(s.totalSubmissions||12542)-rows.length),'No manual review','up')}${dashKpi('Warning',rows.filter(x=>String(x.validation).includes('WARN')).length||321,'Need review','down')}${dashKpi('Error',187,'Rule violation','down')}${dashKpi('Correction',rows.filter(x=>String(x.validation).includes('CORRECTION')).length||54,'Returned to field','down')}</div><div class="section-title"><div><h3>Exception Queue</h3><p>Data Entry fokus pada warning, error, duplicate, dan correction.</p></div><button id="refreshBtn" class="btn btn-secondary btn-sm">Refresh</button></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Time</th><th>NC</th><th>Store</th><th>Module</th><th>Issue</th><th>Severity</th><th>Action</th></tr></thead><tbody>${rows.length?rows.map((r,i)=>`<tr class="submission-row" data-id="${escapeHtml(r.submissionId)}"><td>${shortTime(r.time)}</td><td class="strong">${escapeHtml(r.nc)}</td><td>${escapeHtml(r.store)}</td><td>${escapeHtml(r.task)}</td><td>${issueText(r.validation,r.task)}</td><td>${badge(r.validation)}</td><td><div class="actions"><button class="btn btn-secondary btn-sm validate-btn" data-id="${escapeHtml(r.submissionId)}">Validate</button><button class="btn btn-danger btn-sm correct-btn" data-id="${escapeHtml(r.submissionId)}">Correction</button></div></td></tr>`).join(''):`<tr><td colspan="7" class="empty">Tidak ada exception. Semua data bersih ✓</td></tr>`}</tbody></table></div></div>`;}
function renderQuality(){const s=state.bootstrap.stats;return desktopWorkspace(`<div class="kpi-grid">${dashKpi('Validation Pass',(s.dataAccuracy||96.7)+'%','Validated / total','up')}${dashKpi('Completeness','98.6%','Required fields','up')}${dashKpi('Timeliness','97.8%','On-time submission','up')}${dashKpi('Duplicate Rate','0.4%','Protected by idempotency','up')}${dashKpi('Correction Rate','1.3%','Need field revision','down')}</div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>Errors by Type</h3><p>Exception distribution</p></div></div><div class="region-bars">${qualityBars()}</div></div><div class="panel"><div class="panel-head"><div><h3>Data Quality by Region</h3><p>Validation pass rate</p></div></div><div class="region-bars">${[['Jakarta',99],['West Java',97],['Central Java',95],['East Java',98]].map(([n,v])=>simpleBar(n,v)).join('')}</div></div></div><div class="section-title"><div><h3>Open Exceptions</h3><p>Click a row to inspect submission detail.</p></div></div>${queueCompact()}`);}
function renderNCTracker(){return desktopWorkspace(`<div class="kpi-grid">${dashKpi('Active NC',state.bootstrap.stats.activeNC,'All active manpower','up')}${dashKpi('Attendance','98.1%','Current month','up')}${dashKpi('Visit Completion','95.8%','PJP completion','up')}${dashKpi('Task Completion','96.7%','Mandatory tasks','up')}${dashKpi('Avg Acquisition','41','Per NC','up')}</div><div class="section-title"><div><h3>NC Performance Tracker</h3><p>Click row for individual operational view.</p></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>NC</th><th>Area</th><th>Planned</th><th>Visited</th><th>Completion</th><th>Acquisition</th><th>Status</th></tr></thead><tbody>${ncRows().map(x=>`<tr><td class="strong">${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${progressInline(x[4])}</td><td>${x[5]}</td><td>${badge(x[6])}</td></tr>`).join('')}</tbody></table></div></div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><h3>Top Visit Completion</h3></div><div class="region-bars">${ncRows().slice(0,4).map(x=>simpleBar(x[0],x[4])).join('')}</div></div><div class="panel"><div class="panel-head"><h3>Individual Snapshot · NC001</h3></div><div class="panel-pad">${metric('Attendance',98)}${metric('Visit Completion',96)}${metric('Task Completion',97)}${metric('Offtake Achievement',103)}${metric('Acquisition',92)}</div></div></div>`);}
function renderGWP(){return desktopWorkspace(`<div class="kpi-grid">${dashKpi('Allocation','10,000','Units allocated','up')}${dashKpi('Distributed','8,450','Used in field','up')}${dashKpi('Balance','1,550','Remaining','up')}${dashKpi('Absorption','84.5%','Allocation vs use','up')}${dashKpi('Low Stock Stores','12','Need review','down')}</div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>GWP Absorption by Region</h3><p>Current period</p></div></div><div class="region-bars">${[['Jakarta',92],['West Java',86],['Central Java',81],['East Java',79]].map(([n,v])=>simpleBar(n,v)).join('')}</div></div><div class="panel"><div class="panel-head"><div><h3>GWP Balance</h3><p>Illustrative store balance</p></div></div><div class="panel-pad">${metric('Guardian Kemang',88)}${metric('Mothercare Demo Mall',74)}${metric('Kids Corner Cilandak',62)}${metric('Baby House Bandung',45)}</div></div></div>`);}
function renderConsumer(){return desktopWorkspace(`<div class="kpi-grid">${dashKpi('Lead','3,420','New consumer','up')}${dashKpi('Consultation','2,840','83% of lead','up')}${dashKpi('Trial','2,120','75% of consultation','up')}${dashKpi('Purchase','1,485','70% of trial','up')}${dashKpi('Repeat','685','46% of purchase','up')}</div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>Consumer Funnel</h3><p>Lifecycle event view</p></div></div>${consumerFunnel()}</div><div class="panel"><div class="panel-head"><div><h3>Conversion by Region</h3><p>Illustrative demo metric</p></div></div><div class="region-bars">${[['Jakarta',74],['West Java',69],['Central Java',65],['East Java',71]].map(([n,v])=>simpleBar(n,v)).join('')}</div></div></div>`);}
function renderCompetitor(){return desktopWorkspace(`<div class="competitor-cards">${competitorCard(34,'Price Promotion')}${competitorCard(18,'GWP Activity')}${competitorCard(27,'Display / Visibility')}${competitorCard(11,'Sampling')}</div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="panel-head"><div><h3>Competitor Activity Trend</h3><p>Field observation volume</p></div></div>${lineChart([{date:'09-14',value:22},{date:'09-15',value:31},{date:'09-16',value:27},{date:'09-17',value:38},{date:'09-18',value:33},{date:'09-19',value:45},{date:'09-20',value:41}])}</div><div class="panel"><div class="panel-head"><div><h3>Recent Observations</h3><p>Demo market intelligence</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Competitor</th><th>Activity</th><th>Region</th><th>Observation</th></tr></thead><tbody><tr><td class="strong">Brand A</td><td>Price Promo</td><td>Jakarta</td><td>Bundle discount</td></tr><tr><td class="strong">Brand B</td><td>GWP</td><td>West Java</td><td>Free tumbler</td></tr><tr><td class="strong">Brand C</td><td>Display</td><td>Central Java</td><td>End gondola</td></tr></tbody></table></div></div></div>`);}
function renderSystem(){const q=offlineQueue();return `<div class="info-strip">Gunakan halaman ini sebelum pitching untuk mengecek jalur Browser → Vercel → GAS → Google Sheets.</div><div class="grid-3" style="margin-top:12px">${systemCard('1. Vercel Frontend',location.hostname.includes('vercel.app')?'✓ Running on Vercel':'✓ Frontend loaded')}${systemCard('2. GAS Backend',state.connected?'✓ Connected':'⚠ Fallback active')}${systemCard('3. Offline Queue',`${q.length} item waiting`)}</div><div class="panel panel-pad" style="margin-top:14px"><div class="panel-head" style="padding:0 0 12px;border:0"><h3>One-click Health Check</h3><button id="healthBtn" class="btn btn-primary btn-sm">Check Now</button></div><div id="healthResult" class="muted" style="font-size:11px">Klik Check Now. Hasil harus menunjukkan backend aktif sebelum pitching.</div></div>`;}

/* ---------- WORKSPACE HELPERS ---------- */
function desktopWorkspace(content){return `<div class="page-grid">${filterRail()}<div class="dashboard-content">${content}</div></div>`;}
function filterRail(){return `<aside class="filter-rail"><h4>Filter By</h4>${filterField('Period',['Sep 2027','Aug 2027','Jul 2027'])}${filterField('Region',['All','Jakarta','West Java','Central Java','East Java'])}${filterField('Area',['All','South Jakarta','Bandung','Semarang'])}${filterField('Channel',['All','Baby Shop','Modern Trade'])}${filterField('TL',['All','Andi','Rina','Budi'])}${filterField('NC',['All','NC001','NC002','NC003'])}${filterField('Store',['All','Guardian Kemang','Mothercare Demo Mall'])}${filterField('Product',['All','Enfagrow A+ 400g','Enfagrow A+ 800g'])}<div class="filter-actions"><button id="applyFilter" class="btn btn-primary">Apply</button><button id="resetFilter" class="btn btn-ghost">Reset</button></div></aside>`;}
function filterField(label,opts){return `<div class="filter-field"><label>${label}</label><select>${opts.map(x=>`<option>${x}</option>`).join('')}</select></div>`;}
function dashKpi(label,value,note,dir){return `<div class="kpi-card"><div class="kpi-label">${escapeHtml(label)}</div><div class="kpi-value">${escapeHtml(String(value))}</div><div class="kpi-note">${escapeHtml(note)}</div>${dir?`<div class="kpi-delta ${dir}">${dir==='up'?'↑':'↓'} ${dir==='up'?'Healthy':'Review'}</div>`:''}</div>`;}
function mobileStat(v,l){return `<div class="mobile-stat"><b>${escapeHtml(String(v))}</b><span>${escapeHtml(l)}</span></div>`;}
function quick(icon,label,page){return `<button class="quick-card" onclick="go('${page}')"><span class="quick-icon">${icon}</span><span>${label}</span></button>`;}
function visitCard(x,i,detail=false){return `<div class="visit-card"><div class="visit-number">${i+1}</div><div><h4>${escapeHtml(x.storeName)}</h4><p>${escapeHtml(x.plannedStart)}–${escapeHtml(x.plannedEnd)} · South Jakarta</p><div class="progress"><span style="width:${Number(x.completion||0)}%"></span></div><small>${x.completion||0}% task completed</small></div><button class="btn btn-sm ${x.status==='COMPLETED'?'btn-secondary':'btn-primary'}" onclick="go('${x.status==='COMPLETED'?'history':'tasks'}')">${x.status==='COMPLETED'?'View':'Start'}</button></div>`;}
function syncBox(i,v,l){return `<div class="sync-box"><span style="font-size:16px">${i}</span><b>${v}</b><span>${l}</span></div>`;}
function miniProfile(l,v){return `<div class="detail-cell"><label>${l}</label><b>${v}</b></div>`;}
function lineChart(trend){const arr=trend.length?trend:[{date:'09-14',value:142},{date:'09-15',value:151},{date:'09-16',value:160},{date:'09-17',value:169},{date:'09-18',value:178},{date:'09-19',value:187},{date:'09-20',value:196}], vals=arr.map(x=>Number(x.value)||0),min=Math.min(...vals)*.9,max=Math.max(...vals)*1.08,pts=vals.map((v,i)=>{const x=35+i*(450/Math.max(1,vals.length-1)),y=185-((v-min)/(max-min||1))*135;return [x,y];}),path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '),area=`${path} L ${pts[pts.length-1][0]} 190 L ${pts[0][0]} 190 Z`;
  return `<div class="chart-shell"><svg class="chart-svg" viewBox="0 0 520 210" role="img" aria-label="Performance trend"><defs><linearGradient id="lineGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#79bdff" stop-opacity=".65"/><stop offset="1" stop-color="#eaf4ff" stop-opacity=".1"/></linearGradient></defs><line x1="35" y1="50" x2="485" y2="50" stroke="#edf2f7"/><line x1="35" y1="95" x2="485" y2="95" stroke="#edf2f7"/><line x1="35" y1="140" x2="485" y2="140" stroke="#edf2f7"/><path class="area-main" d="${area}"/><path class="line-target" d="M35 105 L485 105"/><path class="line-main" d="${path}"/>${pts.map(p=>`<circle class="chart-point" cx="${p[0]}" cy="${p[1]}" r="5"/>`).join('')}${arr.map((x,i)=>`<text class="axis-label" x="${pts[i][0]}" y="204" text-anchor="middle">${String(x.date).slice(-5)}</text>`).join('')}</svg></div>`;}
function regionBars(rows){const a=rows.length?rows:[{region:'Jakarta',achievement:103},{region:'West Java',achievement:98},{region:'Central Java',achievement:93},{region:'East Java',achievement:101}];return `<div class="region-bars">${a.map(r=>simpleBar(r.region,Number(r.achievement)||0,115)).join('')}</div>`;}
function simpleBar(n,v,max=100){return `<div class="region-bar"><label>${escapeHtml(n)}</label><div class="region-track"><span style="width:${Math.min(100,(v/max)*100)}%"></span></div><b>${Number(v).toFixed(v%1?1:0)}%</b></div>`;}
function metric(n,v,inverse=false){return `<div class="metric-row"><label>${n}</label><div class="progress"><span style="width:${Math.min(100,Number(v))}%;${inverse?'background:linear-gradient(90deg,#f7b84b,#f59e0b)':''}"></span></div><b>${v}%</b></div>`;}
function insightCard(){return `<div class="insight-card"><h4>Acquisition · Achievement 91%</h4><div class="insight-line"><b>Observation</b><span>Acquisition turun 6.4% dibanding periode sebelumnya.</span></div><div class="insight-line"><b>Supporting metric</b><span>Store coverage turun 5.8% pada tiga area.</span></div><div class="insight-line"><b>Potential driver</b><span>Penurunan visit completion berasosiasi dengan penurunan acquisition.</span></div><div class="insight-line"><b>Recommended review</b><span>Review missed PJP dan low-coverage stores sebelum menetapkan tindakan.</span></div></div>`;}
function regionTable(rows){return `<div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Region</th><th>Target</th><th>Actual</th><th>Achievement</th><th>Gap</th><th>Trend</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="strong">${escapeHtml(r.region)}</td><td>${num(r.target)}</td><td>${num(r.actual)}</td><td>${badge('ACH '+r.achievement+'%')}</td><td>${num(r.actual-r.target)}</td><td>${r.achievement>=100?'↑':'→'}</td></tr>`).join('')}</tbody></table></div></div>`;}
function qualityBars(){return [['Missing Data',42],['Duplicate',18],['GPS Mismatch',26],['Outlier',34],['Late Submission',58]].map(([n,v])=>simpleBar(n,v,60)).join('');}
function queueCompact(){const rows=state.bootstrap.queue||[];return `<div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Time</th><th>NC</th><th>Store</th><th>Module</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr class="submission-row" data-id="${escapeHtml(r.submissionId)}"><td>${shortTime(r.time)}</td><td class="strong">${escapeHtml(r.nc)}</td><td>${escapeHtml(r.store)}</td><td>${escapeHtml(r.task)}</td><td>${badge(r.validation)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function ncRows(){return [['Mimo Rahma','South Jakarta',20,19,95,42,'GOOD'],['Dinda Ayu','Bandung',20,17,85,31,'REVIEW'],['Rani Dewi','Semarang',18,18,100,46,'GOOD'],['Salsa Putri','East Jakarta',20,19,95,44,'GOOD'],['Nadia Sari','Bogor',18,16,89,36,'REVIEW']];}
function progressInline(v){return `<div style="display:flex;align-items:center;gap:7px"><div class="progress" style="width:90px"><span style="width:${v}%"></span></div><b style="font-size:9px">${v}%</b></div>`;}
function consumerFunnel(){const items=[['Lead',3420,100],['Consultation',2840,86],['Trial',2120,70],['Purchase',1485,56],['Repeat',685,38]];return `<div class="funnel">${items.map(([n,v,w])=>`<div class="funnel-step" style="width:${w}%"><b>${n}</b><span>${num(v)}</span></div>`).join('')}</div>`;}
function competitorCard(v,l){return `<div class="competitor-card"><b>${v}</b><span>${l}</span></div>`;}
function systemCard(t,v){return `<div class="panel panel-pad"><div class="kpi-label">${t}</div><div style="font-size:12px;font-weight:800;color:#123C73;margin-top:8px">${v}</div></div>`;}
function issueText(status,task){const s=String(status||'');if(s.includes('CORRECTION'))return 'Correction requested';if(s.includes('WARNING'))return task==='Stock Taking'?'Stock gap high':'Value outlier';return 'Rule exception';}
function badge(status){const s=String(status||'').toUpperCase();let c='badge-muted';if(s.includes('VALID')||s.includes('GOOD')||s.includes('COMPLETED')||s.includes('ACH 10')||s.includes('ACH 11'))c='badge-ok';else if(s.includes('WARN')||s.includes('REVIEW')||s.includes('IN_PROGRESS')||s.includes('PLANNED')||s.includes('ACH 9'))c='badge-warn';else if(s.includes('ERROR')||s.includes('CORRECTION')||s.includes('REJECT'))c='badge-danger';else c='badge-blue';return `<span class="badge ${c}">${escapeHtml(status)}</span>`;}

/* ---------- MODALS / ACTIONS ---------- */
function openSubmissionModal(id){const r=(state.bootstrap.queue||[]).find(x=>x.submissionId===id)||{submissionId:id,nc:'Mimo Rahma',store:'Guardian Kemang',task:'Stock Taking',validation:'WARNING',time:new Date().toISOString()};state.selectedSubmission=r;$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h3>Submission Detail</h3><button class="icon-button" onclick="closeModal()">×</button></div><div class="modal-body"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:13px"><div><span class="overline">${escapeHtml(shortId(r.submissionId))}</span><h3 style="margin:3px 0;color:#123C73">${escapeHtml(r.task)}</h3></div>${badge(r.validation)}</div><div class="modal-grid">${detail('NC',r.nc)}${detail('Store',r.store)}${detail('Submitted',shortTime(r.time))}${detail('GPS','86 m from store')}${detail('System Stock','40')}${detail('Physical Stock','5')}${detail('Difference','-35')}${detail('Evidence','1 photo')}</div><div class="info-strip" style="margin-top:13px"><b>Validation warning:</b> Stock difference exceeds demo threshold. Review before inclusion in clean KPI data.</div></div><div class="modal-actions"><button class="btn btn-secondary" onclick="modalValidate('${escapeJs(id)}')">Validate</button><button class="btn btn-danger" onclick="openCorrectionModal('${escapeJs(id)}')">Request Correction</button><button class="btn btn-ghost" onclick="closeModal()">Close</button></div></div></div>`;}
function detail(l,v){return `<div class="detail-cell"><label>${l}</label><b>${escapeHtml(v)}</b></div>`;}
function openCorrectionModal(id){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>Correction Required</h3><button class="icon-button" onclick="closeModal()">×</button></div><div class="modal-body"><div class="field"><label>Reason</label><select id="correctionReason"><option>Wrong Quantity</option><option>Wrong SKU</option><option>Missing Evidence</option><option>GPS Issue</option><option>Other</option></select></div><div class="field" style="margin-top:12px"><label>Message to NC</label><textarea id="correctionMessage">Please verify physical stock and submit again.</textarea></div></div><div class="modal-actions"><button class="btn btn-danger" onclick="sendCorrection('${escapeJs(id)}')">Send Correction</button><button class="btn btn-ghost" onclick="closeModal()">Cancel</button></div></div></div>`;}
function closeModal(){$('#modalRoot').innerHTML='';} window.closeModal=closeModal;
async function modalValidate(id){closeModal();await validationDecision(id,'VALIDATE');} window.modalValidate=modalValidate;
async function sendCorrection(id){const reason=$('#correctionMessage')?.value||$('#correctionReason')?.value||'Please verify field data.';closeModal();await validationDecision(id,'CORRECTION',reason);} window.sendCorrection=sendCorrection; window.openCorrectionModal=openCorrectionModal;
async function validationDecision(submissionId,decision,reason){reason=reason||(decision==='CORRECTION'?'Please verify field data.':'Approved during manual review');try{const d=await api('updateValidation',{submissionId,userId:state.user.userId,decision,reason});toast(d.message||'Status diperbarui');await loadBootstrap();}catch(err){if(state.bootstrap&&Array.isArray(state.bootstrap.queue)){state.bootstrap.queue=state.bootstrap.queue.filter(x=>x.submissionId!==submissionId);state.bootstrap.stats.pendingReview=state.bootstrap.queue.length;render();toast(decision==='VALIDATE'?'Validated in demo fallback.':'Correction sent in demo fallback.','warn');}else toast(err.message||'Gagal memperbarui','error');}}

/* ---------- FORMS / API ---------- */
async function submitStock(e){e.preventDefault();const fd=new FormData(e.currentTarget),p=baseSubmissionPayload('submitStock');Object.assign(p,{storeId:fd.get('storeId'),productId:fd.get('productId'),systemStock:Number(fd.get('systemStock')),physicalStock:Number(fd.get('physicalStock')),remark:fd.get('remark')||''});await sendOrQueue('submitStock',p,e.currentTarget);}
async function submitOfftake(e){e.preventDefault();const fd=new FormData(e.currentTarget),p=baseSubmissionPayload('submitOfftake');Object.assign(p,{storeId:fd.get('storeId'),productId:fd.get('productId'),quantity:Number(fd.get('quantity')),value:Number(fd.get('value')||0),source:fd.get('source')});await sendOrQueue('submitOfftake',p,e.currentTarget);}
function baseSubmissionPayload(action){return {action,userId:state.user.userId,deviceTimestamp:new Date().toISOString(),idempotencyKey:crypto.randomUUID?crypto.randomUUID():`local-${Date.now()}-${Math.random()}`,syncSource:navigator.onLine?'ONLINE':'OFFLINE_QUEUE'};}
async function sendOrQueue(action,payload,form){const btn=form.querySelector('button[type="submit"]'),old=btn.textContent;btn.disabled=true;btn.textContent='Saving…';try{const d=await api(action,payload);toast(d.message||'Data tersimpan');await loadBootstrap();go('history');}catch(_){queueOffline(action,payload);toast('Data disimpan di Offline Queue dan akan auto-sync.','warn');go('sync');}finally{btn.disabled=false;btn.textContent=old;}}
function updateStockDiff(){const a=Number($('#systemStock')?.value||0),b=Number($('#physicalStock')?.value||0),el=$('#stockDiff');if(!el)return;const d=b-a;el.textContent=(d>0?'+':'')+d;el.style.color=Math.abs(d)>20?'#E5484D':'#123C73';}
function previewEvidence(){const f=$('#evidenceInput')?.files?.[0];if(f)$('#evidenceLabel').textContent=f.name;}
function storeSelect(){return `<div class="field"><label>Store · from PJP</label><select name="storeId" required><option value="STR-JKS-001">Guardian Kemang</option><option value="STR-JKS-002">Mothercare Demo Mall</option><option value="STR-JKS-003">Kids Corner Cilandak</option></select></div>`;}
function productSelect(){return `<div class="field"><label>Product / SKU</label><select name="productId" required><option value="PRD-EFA-400">Enfagrow A+ 400g</option><option value="PRD-EFA-800">Enfagrow A+ 800g</option><option value="PRD-EFA-1200">Enfagrow A+ 1200g</option></select></div>`;}
async function api(action,payload){const r=await fetch('/api/gas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({ok:false,message:'Response bukan JSON'}));if(!r.ok||d.ok===false)throw new Error(d.message||d.error||'API error');return d;}
async function checkHealth(){const el=$('#healthResult');el.textContent='Checking…';try{const d=await api('health',{});state.connected=true;setConnection(true,'GAS connected');el.innerHTML=`✓ <b>Semua jalur aktif.</b> Database: ${escapeHtml(d.database||'Google Sheets')} · ${escapeHtml(d.sheets||'')} tabs · ${shortTime(d.now)}`;}catch(err){state.connected=false;setConnection(false,'Offline demo fallback');el.innerHTML=`⚠ ${escapeHtml(err.message)}. Fallback UI tetap aktif.`;}}
function queueOffline(action,payload){const q=offlineQueue();q.push({action,payload,queuedAt:new Date().toISOString()});localStorage.setItem('nc2027_offline_queue',JSON.stringify(q));updateOfflineBadge();}
function offlineQueue(){return safeJson(localStorage.getItem('nc2027_offline_queue'))||[];}
async function flushOfflineQueue(){const q=offlineQueue();if(!q.length){toast('Tidak ada data yang menunggu sync.');return;}const remain=[];for(const item of q){try{await api(item.action,{...item.payload,syncSource:'OFFLINE_QUEUE'});}catch(_){remain.push(item);}}localStorage.setItem('nc2027_offline_queue',JSON.stringify(remain));updateOfflineBadge();if(!remain.length){toast(`${q.length} item berhasil disinkronkan.`);await loadBootstrap();}else toast(`${remain.length} item masih menunggu backend.`,'warn');}
function updateOfflineBadge(){const e=$('#offlineBadge');if(!e)return;const n=offlineQueue().length;e.textContent=`${n} pending sync`;e.classList.toggle('hidden',n===0);}
function setConnection(on,text){const d=$('#connectionDot'),l=$('#connectionText');if(!d||!l)return;d.classList.remove('online','offline');d.classList.add(on?'online':'offline');l.textContent=text;}
function logout(){localStorage.removeItem('nc2027_user');state.user=null;state.bootstrap=null;$('#appShell').classList.add('hidden');$('#loginScreen').classList.remove('hidden');document.body.dataset.role='';} window.logout=logout;

/* ---------- FALLBACK / FORMAT ---------- */
function localLogin(code,pin){if(pin!=='1234')return null;const m={NC001:['USR-NC001','Mimo Rahma','NC'],DE001:['USR-DE001','Admin Data','DATA_ENTRY'],DA001:['USR-DA001','Data Analyst','DATA_ANALYST'],PM001:['USR-PM001','Project Manager','PROJECT_MANAGER']},x=m[code];return x?{userId:x[0],employeeCode:code,fullName:x[1],role:x[2],status:'ACTIVE'}:null;}
function mockTasks(){return [{visitId:'V1',storeId:'STR-JKS-001',storeName:'Guardian Kemang',plannedStart:'09:00',plannedEnd:'11:00',status:'COMPLETED',completion:100},{visitId:'V2',storeId:'STR-JKS-002',storeName:'Mothercare Demo Mall',plannedStart:'11:30',plannedEnd:'13:30',status:'IN_PROGRESS',completion:65},{visitId:'V3',storeId:'STR-JKS-003',storeName:'Kids Corner Cilandak',plannedStart:'14:00',plannedEnd:'16:00',status:'PLANNED',completion:0}];}
function fallbackBootstrap(user){const today=new Date(),trend=[];for(let i=6;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);trend.push({date:d.toISOString().slice(0,10),value:142+(6-i)*9+(i%2?3:-2)});}const queue=[{submissionId:'SUB-DEMO-3',time:new Date(Date.now()-42*60000).toISOString(),nc:'Dinda Ayu',store:'Baby House Bandung',task:'Stock Taking',validation:'WARNING'},{submissionId:'SUB-DEMO-4',time:new Date(Date.now()-55*60000).toISOString(),nc:'Rani Dewi',store:'Little Star Semarang',task:'Offtake',validation:'CORRECTION_REQUIRED'}];return {ok:true,user,stats:{activeNC:286,activeStores:1248,storeCoverage:93,taskCompletion:96.7,acquisition:3420,conversion:1485,offtake:92,gwpAbsorption:84.5,dataAccuracy:99.2,totalSubmissions:12542,pendingReview:2},trend,regionPerformance:[{region:'Jakarta',target:12000,actual:12360,achievement:103},{region:'West Java',target:10000,actual:9800,achievement:98},{region:'Central Java',target:8000,actual:7440,achievement:93},{region:'East Java',target:9000,actual:9090,achievement:101}],tasks:user.role==='NC'?mockTasks():[],queue:user.role==='NC'?[]:queue,recentSubmissions:[{submissionId:'SUB-DEMO-1',time:new Date().toISOString(),nc:'Mimo Rahma',store:'Guardian Kemang',task:'Stock Taking',status:'VALIDATED'},{submissionId:'SUB-DEMO-2',time:new Date(Date.now()-20*60000).toISOString(),nc:'Mimo Rahma',store:'Mothercare Demo Mall',task:'Offtake',status:'VALIDATED'}],system:{ok:false,database:'Offline Fallback'}};}
function initials(n){return String(n||'NC').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}function firstName(n){return String(n||'').split(/\s+/)[0];}
function shortId(id){const s=String(id||'');return s.length>18?s.slice(0,8)+'…'+s.slice(-5):s;}function shortTime(v){const d=new Date(v);return isNaN(d)?String(v||''):`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} · ${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}`;}
function formatLongDate(d){return d.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});}function formatShortDate(d){return d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'});}function num(n){return new Intl.NumberFormat('id-ID').format(Number(n||0));}
function safeJson(v){try{return JSON.parse(v)}catch(_){return null}}function escapeHtml(v){return String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}function escapeJs(v){return String(v||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
function toast(msg,type=''){const e=$('#toast');e.textContent=msg;e.className=`toast show ${type}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.className='toast',3000);}
